name: Scala Steward

on:
  schedule:
    - cron: "0 0 * * 5"  # runs every Friday at midnight
  workflow_dispatch:     # allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install npm dependencies so that it brings TypeScript for Scala Steward
        run: |
          npm install

      - name: Run Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          branches: scala-steward
